# HTTP to HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name *.reconta.app reconta.app;
    return 301 https://$host$request_uri;
}

# WWW to non-WWW redirect
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/reconta.app/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/reconta.app/privkey.pem;

    server_name www.reconta.app;
    return 301 https://reconta.app$request_uri;
}

# Main application server
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/reconta.app/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/reconta.app/privkey.pem;

    server_name *.reconta.app reconta.app;

    location / {
        proxy_pass http://localhost:3020; # Your Next.js app port
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
